///////////////////////////////////////////////////////////
//                                                       //
//                    WgFoundation.h                     //
//                                                       //
//  - Interface for Foundation class                     //
//                                                       //
//  - Written By Woong Gyu La a.k.a. Chris               //
//       on 2009.10.01                                   //
//                                                       //
///////////////////////////////////////////////////////////

#ifndef __WG3D_FOUNDATION_H__
#define __WG3D_FOUNDATION_H__

// collision
// #include "WgBoundingVolumeTree.h"
// #include "WgBoxBVTree.h"
// #include "WgCollisionGroup.h"
// #include "WgCollisionRecord.h"
// #include "WgSphereBVTree.h"

// containment

//#include "WgContBox3.h"
#include "WgContSphere3.h"

// controllers
#include "WgController.h"
// #include "WgIKController.h"
// #include "WgIKGoal.h"
// #include "WgIKJoint.h"
// #include "WgKeyframeController.h"
// #include "WgMorphController.h"
// #include "WgParticleController.h"
// #include "WgPointController.h"
// #include "WgSkinController.h"


// effects
#include "WgBumpMapEffect.h"
#include "WgDarkMapEffect.h"
#include "WgEffect.h"
#include "WgEnvironmentMapEffect.h"
#include "WgGlossMapEffect.h"
#include "WgLightMapEffect.h"
//#include "WgPlanarReflectionEffect.h"
#include "WgPlanarShadowEffect.h"
#include "WgProjectedTextureEffect.h"
#include "WgTextureEffect.h"
#include "WgVertexColorEffect.h"


// intersection
#include "WgIntersector.h"
//#include "WgIntersector1.h"
// #include "WgIntrArc2Arc2.h"
// #include "WgIntrArc2Circle2.h"
// #include "WgIntrBox2Box2.h"
// #include "WgIntrBox2Circle2.h"
// #include "WgIntrBox3Box3.h"
// #include "WgIntrBox3Frustum3.h"
// #include "WgIntrBox3Sphere3.h"
// #include "WgIntrCapsule3Capsule3.h"
// #include "WgIntrCircle2Circle2.h"
// #include "WgIntrCircle3Plane3.h"
// #include "WgIntrEllipse2Ellipse2.h"
// #include "WgIntrLinComp2LinComp2.h"
// #include "WgIntrLinComp2Triangle2.h"
// #include "WgIntrLine2Arc2.h"
// #include "WgIntrLine2Box2.h"
// #include "WgIntrLine2Circle2.h"
// #include "WgIntrLine3Box3.h"
// #include "WgIntrLine3Capsule3.h"
// #include "WgIntrLine3Cone3.h"
// #include "WgIntrLine3Cylinder3.h"
// #include "WgIntrLine3Ellipsoid3.h"
// #include "WgIntrLine3Lozenge3.h"
// #include "WgIntrLine3Plane3.h"
// #include "WgIntrLine3Sphere3.h"
// #include "WgIntrLine3Torus3.h"
// #include "WgIntrLine3Triangle3.h"
// #include "WgIntrLozenge3Lozenge3.h"
// #include "WgIntrPlane3Box3.h"
// #include "WgIntrPlane3Capsule3.h"
// #include "WgIntrPlane3Cylinder3.h"
// #include "WgIntrPlane3Ellipsoid3.h"
// #include "WgIntrPlane3Lozenge3.h"
// #include "WgIntrPlane3Plane3.h"
// #include "WgIntrPlane3Sphere3.h"
// #include "WgIntrPlane3Triangle3.h"
// #include "WgIntrRay2Arc2.h"
// #include "WgIntrRay2Box2.h"
// #include "WgIntrRay2Circle2.h"
// #include "WgIntrRay3Box3.h"
// #include "WgIntrRay3Capsule3.h"
// #include "WgIntrRay3Cylinder3.h"
// #include "WgIntrRay3Ellipsoid3.h"
// #include "WgIntrRay3Lozenge3.h"
// #include "WgIntrRay3Plane3.h"
#include "WgIntrRay3Sphere3.h"
#include "WgIntrRay3Triangle3.h"
// #include "WgIntrSegment2Arc2.h"
// #include "WgIntrSegment2Box2.h"
// #include "WgIntrSegment2Circle2.h"
// #include "WgIntrSegment3Box3.h"
// #include "WgIntrSegment3Capsule3.h"
// #include "WgIntrSegment3Cylinder3.h"
// #include "WgIntrSegment3Ellipsoid3.h"
// #include "WgIntrSegment3Lozenge3.h"
// #include "WgIntrSegment3Plane3.h"
// #include "WgIntrSegment3Sphere3.h"
// #include "WgIntrSegment3Triangle3.h"
// #include "WgIntrSphere3Cone3.h"
// #include "WgIntrSphere3Frustum3.h"
#include "WgIntrSphere3Sphere3.h"
// #include "WgIntrTetrahedron3Tetrahedron3.h"
// #include "WgIntrTriangle2Triangle2.h"
// #include "WgIntrTriangle3Cone3.h"
// #include "WgIntrTriangle3Triangle3.h"

// math
// #include "WgArc2.h"
// #include "WgAxisAlignedBox2.h"
// #include "WgAxisAlignedBox3.h"
// #include "WgBandedMatrix.h"
// #include "WgBox2.h"
// #include "WgBox3.h"
// #include "WgCapsule3.h"
// #include "WgCircle2.h"
// #include "WgCircle3.h"
#include "WgColorRGB.h"
#include "WgColorRGBA.h"
//#include "WgCone3.h"
//#include "WgConvexPolyhedron3.h"
//#include "WgCylinder3.h"
// #include "WgEllipse2.h"
// #include "WgEllipsoid3.h"
#include "WgFrustum3.h"
//#include "WgGMatrix.h"
//#include "WgGVector.h"
#include "WgLinComp.h"
// #include "WgLinComp2.h"
// #include "WgLinComp3.h"
// #include "WgLine2.h"
// #include "WgLine3.h"
// #include "WgLozenge3.h"
// #include "WgMapper2.h"
// #include "WgMapper3.h"
#include "WgMath.h"
#include "WgMatrix2.h"
#include "WgMatrix3.h"
#include "WgMatrix4.h"
#include "WgPlane3.h"
// #include "WgPolyhedron3.h"
// #include "WgPolynomial1.h"
// #include "WgQuadratic2.h"
// #include "WgQuadratic3.h"
 #include "WgQuaternion.h"
#include "WgRay2.h"
#include "WgRay3.h"
// #include "WgRectangle3.h"
// #include "WgSegment2.h"
// #include "WgSegment3.h"
#include "WgSphere3.h"
// #include "WgTetrahedron3.h"
// #include "WgTorus3.h"
// #include "WgTriangle2.h"
#include "WgTriangle3.h"
#include "WgVector2.h"
#include "WgVector3.h"
#include "WgVector4.h"


// object system
#include "WgObject.h"
#include "WgRtti.h"
#include "WgSmartPointer.h"
#include "WgStringTree.h"

// rendering
#include "WgBindInfo.h"
#include "WgBufferParams.h"
#include "WgImage.h"
#include "WgPBuffer.h"
#include "WgRenderer.h"
#include "WgTexture.h"
#include "WgAlphaState.h"
#include "WgCullState.h"
#include "WgDitherState.h"
#include "WgFogState.h"
#include "WgGlobalState.h"
#include "WgMaterialState.h"
#include "WgPolygonOffsetState.h"
#include "WgShadeState.h"
#include "WgStencilState.h"
//#include "WgWireframeState.h"
#include "WgZBufferState.h"


// scene graph
#include "WgBoundingVolume.h"
//#include "WgBoxBV.h"
#include "WgCamera.h"
#include "WgGeometry.h"
#include "WgLight.h"
#include "WgNode.h"
//#include "WgParticles.h"
//#include "WgPolyline.h"
//#include "WgPolypoint.h"
#include "WgScreenPolygon.h"
#include "WgSpatial.h"
#include "WgSphereBV.h"
//#include "WgStandardMesh.h"
#include "WgTransformation.h"
#include "WgTriangles.h"
//#include "WgTriFan.h"
#include "WgTriMesh.h"
//#include "WgTriStrip.h"

// shaders
#include "WgShaderConstant.h"

// shared arrays
#include "WgCachedColorRGBAArray.h"
#include "WgCachedColorRGBArray.h"
//#include "WgCachedIntArray.h"
#include "WgCachedShortArray.h"
#include "WgCachedVector2Array.h"
#include "WgCachedVector3Array.h"
#include "WgColorRGBAArray.h"
#include "WgColorRGBArray.h"
//#include "WgDoubleArray.h"
//#include "WgFloatArray.h"
//#include "WgIntArray.h"
//#include "WgMatrix2Array.h"
//#include "WgMatrix3Array.h"
//#include "WgMatrix4Array.h"
#include "WgShortArray.h"
//#include "WgPlane3Array.h"
#include "WgQuaternionArray.h"
#include "WgTCachedArray.h"
#include "WgTSharedArray.h"
#include "WgVector2Array.h"
#include "WgVector3Array.h"
//#include "WgVector4Array.h"

// system
#include "WgString.h"
#include "WgSystem.h"
#include "WgTArray.h"
//#include "WgTHashSet.h"
#include "WgTHashTable.h"
#include "WgTList.h"
//#include "WgTSet.h"
#include "WgTStack.h"

#endif
